# Generated by Django 4.0.3 on 2022-04-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='media/profile_images/default.jpg', upload_to='profile_images/'),
        ),
    ]
