# Generated by Django 4.0.3 on 2022-04-08 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
