# Generated by Django 4.0.3 on 2022-04-12 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_question_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorited_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
